version: "3"

volumes:
  postgres-data:
    driver: local

services:
  data-hub:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=data_hub
      - POSTGRES_USER=data_hub
      - POSTGRES_PASSWORD=data_hub
    depends_on:
      - postgres
    profiles:
      - disabled

  postgres:
    image: postgis/postgis
    platform: linux/amd64
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=data_hub
      - POSTGRES_USER=data_hub
      - POSTGRES_PASSWORD=data_hub
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./metabase:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    depends_on:
      - postgres
