{
 "title": "Systems",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT upper(country) from communities group by country order by country asc;"
   }
  ]
 },
 "panels": [
  {
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, score\nFROM systems \nWHERE upper(country) in ($country);"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  replace(to_char(sum(population), 'fm999,999,999,999'), ',','.') as population,\n  replace(to_char(sum(households), 'fm999,999,999,999'), ',','.') as households,\n  replace(to_char(sum(households) - sum(households_without_water), 'fm999,999,999,999'), ',','.') as served_households,\n  replace(to_char(sum(households_without_water), 'fm999,999,999,999'), ',','.') as households_without_water\nFROM systems s\nJOIN communities_systems_providers csp ON s.id = csp.system_id\nJOIN communities c ON c.id = csp.community_id\nWHERE upper(s.country) in ($country);"
    }
   ]
  },
  {
   "title": "Systems by score",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(score), score\nFROM systems \nWHERE upper(country) in ($country)\nGROUP BY score\nORDER BY score ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Systems by country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(country_code), country_code FROM systems group by country_code LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last Records",
   "type": "table",
   "description": "<a href=\"/d/f1ba09d3-fe76-47dd-abe6-718fe97074a2/systems-list?orgId=1\" target=\"_blank\">Show all</a>",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT id, name, version, country_code\nFROM systems \nWHERE upper(country) in ($country)\nORDER BY version DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top records",
   "type": "table",
   "description": "<a href=\"/d/f1ba09d3-fe76-47dd-abe6-718fe97074a2/systems-list?orgId=1\" target=\"_blank\">Show all</a>",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT id, name, score, wsi, country_code\nFROM systems \nWHERE upper(country) in ($country)\nORDER BY wsi DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Systems grouped by country",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT country as name, count(*) as value\nFROM systems\nGROUP BY country\nORDER BY 2;"
    },
    {
     "rawSql": "SELECT json_build_object(\n    'type', 'FeatureCollection',\n    'features', json_agg(ST_AsGeoJSON(t.*)::json)\n    ) as geojson\nFROM (SELECT code, name, geom FROM countries\n     ) as t(id, name, geom);"
    }
   ]
  }
 ]
}