{
 "title": "Schools",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT upper(country) from communities group by country order by country asc;"
   }
  ]
 },
 "panels": [
  {
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name,\n  upper(country) as country,\n  concat(adm1, ', ',adm2, ', ',adm3, ', ',adm4) as adm,\n  latitude,\n  longitude,\n  score\nFROM schools \nWHERE upper(country) in ($country);"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  replace(to_char(count(*), 'fm999,999,999,999'), ',','.') as schools,\n  replace(to_char(sum(students_female)+sum(students_male), 'fm999,999,999,999'), ',','.') as students,\n  replace(to_char(sum(staff_women)+sum(staff_men), 'fm999,999,999,999'), ',','.') as staff,\n  (SELECT count(*) FROM schools where have_toilets and upper(country) in ($country)) as have_toilets\nFROM schools\nWHERE upper(country) in ($country);"
    }
   ]
  },
  {
   "title": "Schools by Score",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(score), score\nFROM schools\nWHERE upper(country) in ($country)\nGROUP BY score\nORDER BY score ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Schools by Country",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT country as name, count(*) as value\nFROM schools\nGROUP BY country\nORDER BY 2;"
    },
    {
     "rawSql": "SELECT json_build_object(\n    'type', 'FeatureCollection',\n    'features', json_agg(ST_AsGeoJSON(t.*)::json)\n    ) as geojson\nFROM (SELECT code, name, geom FROM countries\n     ) as t(id, name, geom);"
    }
   ]
  },
  {
   "title": "Last records",
   "type": "table",
   "description": "<a href=\"/d/e28fd4ec-7da0-468f-a0c6-721d1a3c8374/schools-list\" target=\"_blank\">Show all</a>",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT id, name, version, country\nFROM schools\nWHERE upper(country) in ($country)\nORDER BY version DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top records",
   "type": "table",
   "description": "<a href=\"/d/e28fd4ec-7da0-468f-a0c6-721d1a3c8374/schools-list\" target=\"_blank\">Show all</a>",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT id, name, score, shc,country\nFROM schools\nWHERE upper(country) in ($country)\nORDER BY shc DESC\nLIMIT 10"
    }
   ]
  }
 ]
}