apiVersion: 1

datasources:
  - name: countries
    type: marcusolsson-json-datasource
    uid: ce750c6b-2f9b-4303-ac13-c80de8eacd68
    url: https://data-api.globalsiasar.org/countries
    isDefault: false