apiVersion: 1

datasources:
  - name: hub
    type: postgres
    uid: 0fdb8ba7-3686-48b7-8a92-373004563730
    url: $POSTGRES_HOST:$POSTGRES_PORT
    isDefault: true
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: tru
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false