{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT upper(country) from communities group by country order by country asc;"
   },
   {
    "name": "adm1",
    "label": "Adm 1",
    "query": "SELECT adm1 FROM (   SELECT adm1 FROM communities where upper(country) in ($country) group by adm1   UNION ALL   SELECT adm1 FROM systems where upper(country) in ($country) group by adm1   UNION ALL   SELECT adm1 FROM providers where upper(country) in ($country) group by adm1   UNION ALL   SELECT adm1 FROM schools where upper(country) in ($country) group by adm1   UNION ALL   SELECT adm1 FROM health_centers where upper(country) in ($country) group by adm1 ) as union_all_data GROUP BY adm1 ORDER BY 1 asc;"
   },
   {
    "name": "adm2",
    "label": "Adm 2",
    "query": "SELECT adm2 FROM (   SELECT adm2 FROM communities where adm1 in ($adm1) group by adm2 UNION ALL   SELECT adm2 FROM systems where adm1 in ($adm1) group by adm2 UNION ALL   SELECT adm2 FROM providers where adm1 in ($adm1) group by adm2 UNION ALL   SELECT adm2 FROM schools where adm1 in ($adm1) group by adm2 UNION ALL   SELECT adm2 FROM health_centers where adm1 in ($adm1) group by adm2 ) as union_all_data GROUP BY adm2 ORDER BY 1 asc;"
   }
  ]
 },
 "panels": [
  {
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name, st_asgeojson(geom) as geometry\nFROM countries\nWHERE enabled;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as communities\nFROM communities\nWHERE upper(country) in ($country)\nAND adm1 in ($adm1)\nAND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT count(*) as systems\nFROM systems\nWHERE upper(country) in ($country)\nAND adm1 in ($adm1)\nAND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT count(*) as providers\nFROM providers\nWHERE upper(country) in ($country)\nAND adm1 in ($adm1)\nAND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT count(*) as schools\nFROM schools \nWHERE upper(country) in ($country)\nAND adm1 in ($adm1)\nAND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT count(*) as health_centers\nFROM health_centers \nWHERE upper(country) in ($country)\nAND adm1 in ($adm1)\nAND adm2 in ($adm2);"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  replace(to_char(sum(population), 'fm999,999,999,999'), ',','.') as population,\n  replace(to_char(sum(households), 'fm999,999,999,999'), ',','.') as households,\n  replace(to_char(sum(households) - sum(households_without_water), 'fm999,999,999,999'), ',','.') as served_households,\n  replace(to_char(sum(households_without_water), 'fm999,999,999,999'), ',','.') as households_without_water\nFROM communities\nWHERE upper(country) in ($country)\nAND adm1 in ($adm1)\nAND adm2 in ($adm2);"
    }
   ]
  },
  {
   "title": "SIASAR entities by Score",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT 'SYS' as entity, count(*) as \"A\" from systems where score = 'A' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'COM' as entity, count(*) as \"A\" from communities where score = 'A' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'SEP' as entity, count(*) as \"A\" from providers where score = 'A' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT 'SYS' as entity, count(*) as \"B\" from systems where score = 'B' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'COM' as entity, count(*) as \"B\" from communities where score = 'B' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'SEP' as entity, count(*) as \"B\" from providers where score = 'B' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT 'SYS' as entity, count(*) as \"C\" from systems where score = 'C' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'COM' as entity, count(*) as \"C\" from communities where score = 'C' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'SEP' as entity, count(*) as \"C\" from providers where score = 'C' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT 'SYS' as entity, count(*) as \"D\" from systems where score = 'D' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'COM' as entity, count(*) as \"D\" from communities where score = 'D' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'SEP' as entity, count(*) as \"D\" from providers where score = 'D' and upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2);"
    }
   ]
  },
  {
   "title": "SIASAR entities by Country",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT upper(country) as country, count(*) as communities from communities where upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) GROUP BY country;"
    },
    {
     "rawSql": "SELECT upper(country) as country, count(*) as systems from systems where upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) GROUP BY country;"
    },
    {
     "rawSql": "SELECT upper(country) as country, count(*) as providers from providers where upper(country) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) GROUP BY country;"
    }
   ]
  },
  {
   "title": "Gathered Data (Last 6 Months)",
   "type": "barchart",
   "description": "Last 6 Months",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT concat(extract(year from version), '-',extract(month from version)) as label, COUNT(*) as communities\nFROM communities\nWHERE upper(country) in ($country)\nAND adm1 in ($adm1) AND adm2 in ($adm2)\nAND version >= CURRENT_DATE - interval '6 months'\ngroup by extract(year from version), extract(month from version)\nORDER by 1, 2;"
    },
    {
     "rawSql": "SELECT concat(extract(year from version), '-',extract(month from version)) as label, COUNT(*) as systems\nFROM systems\nWHERE upper(country) in ($country)\nAND adm1 in ($adm1) AND adm2 in ($adm2)\nAND version >= CURRENT_DATE - interval '6 months'\ngroup by extract(year from version), extract(month from version)\nORDER by 1, 2;"
    },
    {
     "rawSql": "SELECT concat(extract(year from version), '-',extract(month from version)) as label, COUNT(*) as providers\nFROM providers \nWHERE upper(country) in ($country)\nAND adm1 in ($adm1) AND adm2 in ($adm2)\nAND version >= CURRENT_DATE - interval '6 months'\ngroup by extract(year from version), extract(month from version)\nORDER by 1, 2;"
    }
   ]
  }
 ]
}