{
 "title": "Service Provider Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "id" }
  ]
 },
 "panels": [
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "#### {{country}}\n# {{name}}\n#### {{adm1}}, {{adm2}}, {{adm3}}, {{adm4}}\n{{id}}    \n{{date}}"
   },
   "targets": [
    {
     "rawSql": "select \n  name,\n  id,\n  to_char(version, 'YYYY-MM-DD') as date,\n  country,\n  adm1,\n  adm2,\n  adm3,\n  adm4\nfrom providers \nWHERE id = '${id}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT score\nfrom providers\nwhere id = '${id}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  replace(to_char(sum(population), 'fm999,999,999,999'), ',','.') as population,\n  replace(to_char(sum(households), 'fm999,999,999,999'), ',','.') as households,\n  replace(to_char(sum(households) - sum(households_without_water), 'fm999,999,999,999'), ',','.') as served_households,\n  replace(to_char(sum(households_without_water), 'fm999,999,999,999'), ',','.') as households_without_water\nFROM communities c\nJOIN communities_systems_providers csp ON c.id = csp.community_id\nWHERE csp.provider_id = '${id}';"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, score, image_url\nFROM providers\nWHERE id = '${id}'\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT latitude, longitude, score, image_url\nFROM communities c\nJOIN communities_systems_providers sc ON sc.community_id = c.id\nWHERE sc.provider_id = '${id}'\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT latitude, longitude, score, image_url\nFROM systems s\nJOIN communities_systems_providers sc ON sc.system_id = s.id\nWHERE sc.provider_id = '${id}'\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  image_url\nFROM providers \nWHERE id = '${id}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Communities",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT id, name, score\nFROM communities_systems_providers csp\nJOIN communities c on csp.community_id = c.id\nWHERE csp.provider_id = '${id}'\nGROUP BY id, name, score"
    }
   ]
  },
  {
   "title": "Systems",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT id, name, score\nFROM communities_systems_providers csp\nJOIN systems s on csp.system_id = s.id\nWHERE csp.provider_id = '${id}'\nGROUP BY id, name, score"
    }
   ]
  },
  {
   "title": "Relationships",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT json_agg(\n  json_build_object(\n    'community_id', c.id,\n    'community', c.name,\n    'community_color', color(c.score),\n    'community_adm3', c.adm3,\n    'provider_id', p.id,\n    'provider', p.name,\n    'provider_color', color(p.score),\n    'system_id', s.id,\n    'system', s.name,\n    'system_color', color(s.score),\n    'households', csp.served_households\n  )\n)\nFROM providers p\nLEFT JOIN communities_systems_providers csp on p.id = csp.provider_id\nLEFT JOIN communities c on c.id = csp.community_id\nLEFT JOIN systems s on s.id = csp.system_id\nWHERE p.id = '${id}';"
    }
   ]
  }
 ]
}