{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT upper(adm0) from communities group by adm0 order by adm0 asc;"
   },
   {
    "name": "adm1",
    "label": "Adm 1",
    "query": "SELECT adm1 FROM communities where upper(adm0) in ($country) group by adm1 order by 1 asc;"
   },
   {
    "name": "adm2",
    "label": "Adm 2",
    "query": "SELECT adm2 FROM communities where adm1 in ($adm1) group by adm2 order by 1 asc;"
   }
  ]
 },
 "panels": [
  {
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.features[*].geometry" },
      { "jsonPath": "$.features[*].properties.name", "language": "jsonpath", "name": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as communities\nFROM communities\nWHERE upper(adm0) in ($country)\nAND adm1 in ($adm1)\nAND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT count(*) as systems\nFROM systems\nWHERE upper(adm0) in ($country)\nAND adm1 in ($adm1)\nAND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT count(*) as providers\nFROM providers\nWHERE upper(adm0) in ($country)\nAND adm1 in ($adm1)\nAND adm2 in ($adm2);"
    }
   ]
  },
  {
   "title": "SIASAR entities grouped by country",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT upper(country) as country, count(*) as communities from communities where upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) GROUP BY country;"
    },
    {
     "rawSql": "SELECT upper(country) as country, count(*) as systems from systems where upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) GROUP BY country;"
    },
    {
     "rawSql": "SELECT upper(country) as country, count(*) as providers from providers where upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) GROUP BY country;"
    }
   ]
  },
  {
   "title": "SIASAR entities clasified by score",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT 'SYS' as entity, count(*) as \"A\" from systems where wsi = 'A' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'COM' as entity, count(*) as \"A\" from communities where wsp = 'A' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'SEP' as entity, count(*) as \"A\" from providers where sep = 'A' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT 'SYS' as entity, count(*) as \"B\" from systems where wsi = 'B' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'COM' as entity, count(*) as \"B\" from communities where wsp = 'B' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'SEP' as entity, count(*) as \"B\" from providers where sep = 'B' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT 'SYS' as entity, count(*) as \"C\" from systems where wsi = 'C' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'COM' as entity, count(*) as \"C\" from communities where wsp = 'C' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'SEP' as entity, count(*) as \"C\" from providers where sep = 'C' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2);"
    },
    {
     "rawSql": "SELECT 'SYS' as entity, count(*) as \"D\" from systems where wsi = 'D' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'COM' as entity, count(*) as \"D\" from communities where wsp = 'D' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2) UNION\nSELECT 'SEP' as entity, count(*) as \"D\" from providers where sep = 'D' and upper(adm0) in ($country) AND adm1 in ($adm1) AND adm2 in ($adm2);"
    }
   ]
  },
  {
   "title": "Gathered Data (Last 6 Months)",
   "type": "barchart",
   "description": "Last 6 Months",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT concat(extract(year from version), '-',extract(month from version)) as label, COUNT(*) as communities\nFROM communities\nWHERE upper(adm0) in ($country)\nAND adm1 in ($adm1) AND adm2 in ($adm2)\nAND version >= CURRENT_DATE - interval '6 months'\ngroup by extract(year from version), extract(month from version)\nORDER by 1, 2;"
    },
    {
     "rawSql": "SELECT concat(extract(year from version), '-',extract(month from version)) as label, COUNT(*) as systems\nFROM systems\nWHERE upper(adm0) in ($country)\nAND adm1 in ($adm1) AND adm2 in ($adm2)\nAND version >= CURRENT_DATE - interval '6 months'\ngroup by extract(year from version), extract(month from version)\nORDER by 1, 2;"
    },
    {
     "rawSql": "SELECT concat(extract(year from version), '-',extract(month from version)) as label, COUNT(*) as providers\nFROM providers \nWHERE upper(adm0) in ($country)\nAND adm1 in ($adm1) AND adm2 in ($adm2)\nAND version >= CURRENT_DATE - interval '6 months'\ngroup by extract(year from version), extract(month from version)\nORDER by 1, 2;"
    }
   ]
  }
 ]
}