{
 "title": "Systems",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT upper(adm0) from communities group by adm0 order by adm0 asc;"
   }
  ]
 },
 "panels": [
  {
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, wsi\nFROM systems \nWHERE upper(adm0) in ($country);"
    }
   ]
  },
  {
   "title": "Systems by score",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(wsi), wsi\nFROM systems \nWHERE upper(adm0) in ($country)\nGROUP BY wsi\nORDER BY wsi ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Systems by country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(adm0), adm0 FROM systems GROUP BY adm0 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last Records",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT id, name, version, adm0\nFROM systems \nWHERE upper(adm0) in ($country)\nORDER BY version DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top records",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT id, name, wsi, wsi_value, adm0\nFROM systems \nWHERE upper(adm0) in ($country)\nORDER BY wsi_value DESC\nLIMIT 10"
    }
   ]
  }
 ]
}