{
 "title": "Service Providers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT upper(country_code) from communities group by country_code order by country_code asc;"
   }
  ]
 },
 "panels": [
  {
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, sep\nFROM providers \nWHERE upper(country_code) in ($country);"
    }
   ]
  },
  {
   "title": "Service Providers by score",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(sep), sep\nFROM providers \nWHERE upper(country_code) in ($country)\nGROUP BY sep\nORDER BY sep ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Service Providers by country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(country_code), country_code FROM providers group by country_code LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last Records",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT id, name, version, country_code\nFROM providers \nWHERE upper(country_code) in ($country)\nORDER BY version DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top records",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT id, name, sep, sep_value, country_code\nFROM providers \nWHERE upper(country_code) in ($country)\nORDER BY sep_value DESC\nLIMIT 10"
    }
   ]
  }
 ]
}