name: Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          docker build . --tag siasar-hub:$(date +%s)
          docker build ./grafana --tag siasar-grafana:$(date +%s)
