name: Docker

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io

jobs:
  etl:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels)
        id: meta-etl
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/siasar/hub-etl
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta-etl.outputs.tags }}
          labels: ${{ steps.meta-etl.outputs.labels }}

  grafana:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels)
        id: meta-grafana
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/siasar/hub-grafana
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./grafana
          push: true
          tags: ${{ steps.meta-grafana.outputs.tags }}
          labels: ${{ steps.meta-grafana.outputs.labels }}
